### ISSUE TITLE
Test Conventions

### ISSUE THREAD

**Issue by tildedave** [tilteng/web-style-guide#3]
```
# means that it's describing an instance method
. means that it's a class method.
nothing means it's describing something else
This is important because when the stories are output they read like this:

- HtmlUtils:
    - #hasClass:
        should work if the browser supports classList PASSED
        should work if the browser doesn't support classList PASSED

Failure: 
Notification #render renders the formatted notification FAILED

```

**Comment by cohitre** [comment]
discuss

**Comment by cohitre** [comment]
I'd also like to stop using scoped variables and start assigning values to `this` directly:

yes:
```
beforeEach(function() {
  this.eventTracker = {}
});
```

no:
```
var eventTracker;
beforeEach(function() {
  eventTracker = {};
});

```

**Comment by tildedave** [comment]
@cohitre I'm fine with that, removes the let/var/etc issues

**Comment by cohitre** [comment]
We need to document `TestUtils.renderWithContext`

It wraps the component instance with an extra `div` makes it so you can use .innerHTML to get all the markup. The subject component can be accessed by doing 

```
const r = TestUtils.renderWithContext(...);
const subject = r.refs.component;
```

**Comment by tildedave** [comment]
Actually I think I prefer the variable declarations rather than putting things on the text context.  This makes it easier to clean up unused variables.

**Comment by marr** [comment]
I was running into some issues where:
```
beforeEach(function() {
  renderForm()
});
```
was causing pain in that this in the scope of renderForm was undefined, or different than the test's this.

**Comment by rtymchyk** [comment]
Maybe it's just me, but it wasn't super clear that we should be focused on testing the DOM (via render), versus helper methods defined in the component. I think we should include that somewhere :)

**Comment by rtymchyk** [comment]
Also I really like the original proposal by @cohitre for test name conventions.

**Comment by rtymchyk** [comment]
Old discussion, closing.
