### ISSUE TITLE
Airbnb Style Guide

### ISSUE THREAD

**Issue by tildedave** [tilteng/web-style-guide#6]
I'd like us to adopt the airbnb style guide https://github.com/airbnb/javascript

I think having a third party reference that we can point new members to will be helpful.  Also we can peg ourselves to updates and use out of the box plugins for eslint.  Basically my thought is that we should try to track a community style guide rather than inventing our own style.

The big deviations between our present JavaScript style and this guide is:
* 2 space indents vs 4 space indents
* Single variable declaration vs multiple variable declaration (not sure how hard and fast a rule this is in our present code)

I'd like to re-indent the codebase to 2 characters.  I understand this is going to be a pain in the ass.

**Comment by tildedave** [comment]
discuss

**Comment by rtymchyk** [comment]
>I think having a third party reference that we can point new members to will be helpful. Also we can peg ourselves to updates and use out of the box plugins for eslint. Basically my thought is that we should try to track a community style guide rather than inventing our own style.

I don't know how lenient Airbnb is with updates, but an ever changing guide goes against my understanding of what code conventions/style/rules are meant to stand for. I would suggest we fork it and adjust it to what we want (slightly). Correct me if I'm wrong, but I don't think we'll need to update it that often anyway.

>I'd like to re-indent the codebase to 2 characters. I understand this is going to be a pain in the ass.

I think since we're pretty consistent with 4 space indents, that's what matters - so I don't think there's a reason to go to 2.

**Comment by tildedave** [comment]
So my experience is that code style is constantly evolving and changing, rather than being fixed.  The JavaScript community is a great example of this.  From our own project - a year ago, Babel didn't exist and we didn't use it, so every line of code has a `var` statement.  Now we have babel, which supports a lot of new features - so we can use `const` and `let` exclusively.  If our code style was "use `var` everywhere" then how could we adopt a new feature?

You can achieve style consistency with any guide (we could use 3 space indents everywhere and still be consistent)  but by pegging completely to an upstream guide, we have a solid decision process for how to handle new JavaScript language features.

**Comment by cohitre** [comment]
We can do a couple of lint runs using the airbnb .eslint file. We are good on most rules and the ones we are not we can fix easily.

I usually like 2 spaced indents, but I prefer not messing up the commit history. Maybe we can switch the projects 1 by 1 as the number of open PRs goes down?

**Comment by rtymchyk** [comment]
Can we have our linter with that airnb config (or at least a more strict one than we have) running on every branch/PR?

**Comment by rtymchyk** [comment]
We've introduced an airbnb .eslint config file, set up lint check on CI, and got the spaces 4 -> 2 so I'm going to close this.

**Comment by tildedave** [comment]
+1 Roman. Thanks!
